package com.tsystems.bookstore.persistence.entity;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Book2categoryId generated by hbm2java
 */
@Embeddable
public class Book2categoryId implements java.io.Serializable {

	private int bookId;
	private int categoryId;

	public Book2categoryId() {
	}

	public Book2categoryId(int bookId, int categoryId) {
		this.bookId = bookId;
		this.categoryId = categoryId;
	}

	@Column(name = "book_id", nullable = false, precision = 8, scale = 0)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "category_id", nullable = false, precision = 8, scale = 0)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Book2categoryId))
			return false;
		Book2categoryId castOther = (Book2categoryId) other;

		return (this.getBookId() == castOther.getBookId())
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
