package com.tsystems.bookstore.persistence.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Book2genre generated by hbm2java
 */
@Entity
@Table(name = "book2genre", uniqueConstraints = @UniqueConstraint(columnNames = {
		"book_id", "genre_id" }))
public class Book2genre implements java.io.Serializable {

	private Book2genreId id;
	private Genre genre;
	private Book book;

	public Book2genre() {
	}

	public Book2genre(Book2genreId id, Genre genre, Book book) {
		this.id = id;
		this.genre = genre;
		this.book = book;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "genreId", column = @Column(name = "genre_id", nullable = false, precision = 8, scale = 0)) })
	public Book2genreId getId() {
		return this.id;
	}

	public void setId(Book2genreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genre_id", nullable = false, insertable = false, updatable = false)
	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

}
