package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Book2genreId generated by hbm2java
 */
@Embeddable
public class Book2genreId implements java.io.Serializable {

	private int bookId;
	private int genreId;

	public Book2genreId() {
	}

	public Book2genreId(int bookId, int genreId) {
		this.bookId = bookId;
		this.genreId = genreId;
	}

	@Column(name = "book_id", nullable = false, precision = 8, scale = 0)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "genre_id", nullable = false, precision = 8, scale = 0)
	public int getGenreId() {
		return this.genreId;
	}

	public void setGenreId(int genreId) {
		this.genreId = genreId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Book2genreId))
			return false;
		Book2genreId castOther = (Book2genreId) other;

		return (this.getBookId() == castOther.getBookId())
				&& (this.getGenreId() == castOther.getGenreId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getGenreId();
		return result;
	}

}
