package com.tsystems.bookstore.persistence.entity;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Book2category generated by hbm2java
 */
@Entity
@Table(name = "book2category", uniqueConstraints = @UniqueConstraint(columnNames = {
		"book_id", "category_id" }))
public class Book2category implements java.io.Serializable {

	private Book2categoryId id;
	private Book book;
	private Category category;

	public Book2category() {
	}

	public Book2category(Book2categoryId id, Book book, Category category) {
		this.id = id;
		this.book = book;
		this.category = category;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false, precision = 8, scale = 0)) })
	public Book2categoryId getId() {
		return this.id;
	}

	public void setId(Book2categoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false, insertable = false, updatable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
