package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Book2authorId generated by hbm2java
 */
@Embeddable
public class Book2authorId implements java.io.Serializable {

	private int bookId;
	private int authorId;

	public Book2authorId() {
	}

	public Book2authorId(int bookId, int authorId) {
		this.bookId = bookId;
		this.authorId = authorId;
	}

	@Column(name = "book_id", nullable = false, precision = 8, scale = 0)
	public int getBookId() {
		return this.bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	@Column(name = "author_id", nullable = false, precision = 8, scale = 0)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Book2authorId))
			return false;
		Book2authorId castOther = (Book2authorId) other;

		return (this.getBookId() == castOther.getBookId())
				&& (this.getAuthorId() == castOther.getAuthorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBookId();
		result = 37 * result + this.getAuthorId();
		return result;
	}

}
