package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bookreview generated by hbm2java
 */
@Entity
@Table(name = "bookreview")
public class Bookreview implements java.io.Serializable {

	private int id;
	private Book book;
	private Usr usr;
	private Date reviewdate;
	private short rating;
	private String text;
	private char reviewType;
	private String editoralNotice;
	private String job;
	private String position;
	private Date purchaseDate;

	public Bookreview() {
	}

	public Bookreview(int id, Book book, Usr usr, Date reviewdate,
			short rating, char reviewType) {
		this.id = id;
		this.book = book;
		this.usr = usr;
		this.reviewdate = reviewdate;
		this.rating = rating;
		this.reviewType = reviewType;
	}

	public Bookreview(int id, Book book, Usr usr, Date reviewdate,
			short rating, String text, char reviewType, String editoralNotice,
			String job, String position, Date purchaseDate) {
		this.id = id;
		this.book = book;
		this.usr = usr;
		this.reviewdate = reviewdate;
		this.rating = rating;
		this.text = text;
		this.reviewType = reviewType;
		this.editoralNotice = editoralNotice;
		this.job = job;
		this.position = position;
		this.purchaseDate = purchaseDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usr_id", nullable = false)
	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "reviewdate", nullable = false, length = 10)
	public Date getReviewdate() {
		return this.reviewdate;
	}

	public void setReviewdate(Date reviewdate) {
		this.reviewdate = reviewdate;
	}

	@Column(name = "rating", nullable = false, precision = 3, scale = 0)
	public short getRating() {
		return this.rating;
	}

	public void setRating(short rating) {
		this.rating = rating;
	}

	@Column(name = "text", length = 2000)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "reviewType", nullable = false, length = 1)
	public char getReviewType() {
		return this.reviewType;
	}

	public void setReviewType(char reviewType) {
		this.reviewType = reviewType;
	}

	@Column(name = "editoralNotice", length = 1000)
	public String getEditoralNotice() {
		return this.editoralNotice;
	}

	public void setEditoralNotice(String editoralNotice) {
		this.editoralNotice = editoralNotice;
	}

	@Column(name = "job", length = 50)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "position", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "purchaseDate", length = 10)
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

}
