package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Book2author generated by hbm2java
 */
@Entity
@Table(name = "book2author", uniqueConstraints = @UniqueConstraint(columnNames = {
		"book_id", "author_id" }))
public class Book2author implements java.io.Serializable {

	private Book2authorId id;
	private Author author;
	private Book book;

	public Book2author() {
	}

	public Book2author(Book2authorId id, Author author, Book book) {
		this.id = id;
		this.author = author;
		this.book = book;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bookId", column = @Column(name = "book_id", nullable = false, precision = 8, scale = 0)),
			@AttributeOverride(name = "authorId", column = @Column(name = "author_id", nullable = false, precision = 8, scale = 0)) })
	public Book2authorId getId() {
		return this.id;
	}

	public void setId(Book2authorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "author_id", nullable = false, insertable = false, updatable = false)
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "book_id", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

}
