package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Genre implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<Book2genre> book2genres = new HashSet<Book2genre>(0);

	public Genre() {
	}

	public Genre(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Genre(int id, String name, String description,
			Set<Book2genre> book2genres) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.book2genres = book2genres;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<Book2genre> getBook2genres() {
		return this.book2genres;
	}

	public void setBook2genres(Set<Book2genre> book2genres) {
		this.book2genres = book2genres;
	}

}
