package com.tsystems.bookstore.persistence.entity;
// Generated 26.03.2013 20:03:54 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usr generated by hbm2java
 */
@Entity
@Table(name = "usr")
public class Usr implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;
	private String email;
	private Date regdate;
	private Set<Bookreview> bookreviews = new HashSet<Bookreview>(0);

	public Usr() {
	}

	public Usr(int id, String firstname, String lastname, String email,
			Date regdate) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.regdate = regdate;
	}

	public Usr(int id, String firstname, String lastname, String email,
			Date regdate, Set<Bookreview> bookreviews) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.regdate = regdate;
		this.bookreviews = bookreviews;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 8, scale = 0)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "regdate", nullable = false, length = 19)
	public Date getRegdate() {
		return this.regdate;
	}

	public void setRegdate(Date regdate) {
		this.regdate = regdate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usr")
	public Set<Bookreview> getBookreviews() {
		return this.bookreviews;
	}

	public void setBookreviews(Set<Bookreview> bookreviews) {
		this.bookreviews = bookreviews;
	}

}
